name: hello-world
on: 
  workflow_dispatch:
    inputs:
      person:
        description: input persons name
        required: true
        default: "john doe"
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello ${{ github.event.inputs.tags }}"
