name: hello-world
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'  
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello ${{ github.event.inputs.tags }}"
